<a href="https://colab.research.google.com/github/Tanu-N-Prabhu/Python/blob/master/Numpy/How_to_create_NumPy_arrays_from_scratch%3F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to create NumPy arrays from scratch?

## This tutorial is all about understanding the NumPy python package and creating NumPy arrays from scratch.

![alt text](https://miro.medium.com/max/1148/1*cyXCE-JcBelTyrK-58w6_Q.png)


1.   NumPy Package
2.   Pandas Package



# What is NumPy?

NumPy stands for ***Numerical Python***. NumPy provides an efficient way to store and operate on dense data buffers. With the help of the NumPy library, we can create and operate with arrays to store the data. In some ways, NumPy’s arrays are like Python’s list built-in function.



---



# How to execute NumPy and check its version?

Let’s get started. You can execute the below programs in your favorite python editors like **[PyCharm](https://www.jetbrains.com/pycharm/)**, **[Sublime Text](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/sublime/)**, or Notebooks like **[Jupyter](https://jupyter.org/)** and **[Google Colab](https://colab.research.google.com/notebooks/welcome.ipynb)**. It's basically your preference to choose an IDE of your choice. 

Once you have installed the NumPy on your IDE you need to import it. It’s often a good practice to check the version of the library. So to install the NumPy library you need to use the below code.

In [39]:
import numpy
print(numpy.__version__)

1.18.5


Just make sure that you the latest NumPy version to use all the features and options. Rather than using ***“numpy”*** we can use an alias as ***“np”***. This is called ***“Aliasing”***. Now the point of using an alias is we can use ***“np”*** rather ***“numpy”*** which is long to type every time when we use its methods. So creating an alias and checking the version can be done as shown below:

In [2]:
import numpy as np
print(np.__version__)

1.18.5


From now on we can use “np” rather than “numpy” every time.


---



### Creating a one dimensional array.

In [40]:
# Creating a one dimensional array.
one = np.random.randint(10, size = 6)
print(one)

[0 1 7 6 9 2]


### Creating a two dimensional array.

In [41]:
# Creating a two dimensional array.
two = np.random.randint(10, size = (2, 5))
print(two)

[[4 5 2 4 2]
 [4 7 7 9 1]]


### Creating a three dimensional array.

In [42]:
# Creating a three dimensional array.
three = np.random.randint(10, size = (3, 4, 5))
print(three)

[[[7 0 6 9 9]
  [7 6 9 1 0]
  [1 8 8 3 9]
  [8 7 3 6 5]]

 [[1 9 3 4 8]
  [1 4 0 3 9]
  [2 0 4 9 2]
  [7 7 9 8 6]]

 [[9 3 7 7 4]
  [5 9 3 6 8]
  [0 2 7 7 9]
  [7 3 0 8 7]]]


## Why Numpy arrays came into the picture when there were python’s fixed type arrays?

Python provides several different options for storing efficient, fixed-type data. Python has a built-in array module called “array” which is used to create arrays of uniform type. This was its main disadvantage.

In [6]:
import array
# Creating an array
print(array.array('i', [1, 2, 3, 4, 5]))

array('i', [1, 2, 3, 4, 5])


The ***“i”*** here indicates the integer data. We cannot try to store other types of data in the array module. It often leads to an error.

In [7]:
#import array
# Creating an array
#print(array.array('i', [1, 2.0, 3, 4, 5]))

However, Python’s array module provides efficient storage of array-based data. But NumPy arrays can perform efficient operations on that type of data. There are two ways that we can create NumPy arrays:



1.   Creating a NumPy array from Python Lists
2.   Creating a NumPy array from scratch



# Creating a NumPy array from Python Lists

We can use [**np.array**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html) method to create arrays from python lists.


In [43]:
import numpy as np
# Creating a list named "a"
a = [1, 2, 3, 4, 5]
print(type(a))

<class 'list'>


In [9]:
# Creating a numpy array from the list
print(np.array(a))

[1 2 3 4 5]


In [10]:
print(type(np.array(a)))

<class 'numpy.ndarray'>


The NumPy library is limited to arrays with the same type, if there is a type mismatch then it would upcast if possible. Consider the below example:


In [11]:
import numpy as np
# Creating a list named "a"
a = [1, 2.0, 3, 4, 5]
print(type(a))

<class 'list'>


In [12]:
# Creating a numpy array from the list
print(np.array(a))

[1. 2. 3. 4. 5.]


In [13]:
print(type(np.array(a)))

<class 'numpy.ndarray'>


So the original list was integers with one floating value but the numpy array upcasted it to all ***floating-point*** numbers. The integers are upcasted to floating-point numbers. Below is a small diagram that gives you enough knowledge to understand the upcast and downcast.


![alt text](https://miro.medium.com/max/1374/1*W48CJy96VF86_2JYz1G3QQ.png)

Also explicitly setting the data type is also possible. This can be done using the keyword ***“dtype”***.

In [14]:
import numpy as np
# Creating a list named "a"
a = [1, 2, 3, 4, 5]
# Creating a numpy array from the list
np.array(a, dtype='float64')
print(np.array(a, dtype='float64'))

[1. 2. 3. 4. 5.]


As seen from the above example, the integer type list data is converted into the float type data by using the ***“dtype”*** keyword.
Numpy arrays can also be ***multidimensional*** (Array within an array). Here’s one way of doing it.






---







## Creating an array filled with zeros of length 5




We can do this using the numpy built-in method called zeros as shown below:

In [15]:
import numpy as np
# Creating a numpy array of zeros of length 5
print(np.zeros(5, dtype='int'))

[0 0 0 0 0]


There are some standard numpy data types available. I cannot just discuss all of them in one stretch. Most of them are never used. So I will be providing the data types of numpy array in the form of a chart below just use that accordingly. If you don't know how to use the datatypes refer to **Explicitly changing the array datatypes** above its → ***dtypes = “name of the datatype”***


![alt text](https://miro.medium.com/max/930/1*lbPigku_qn_NeKAHHTGYPg.png)



---



# ##1) Create a length-10 integer array filled with zeros

In [44]:
import numpy as np
a = np.zeros(10, dtype = int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Creating a 3 x 4 array filled with 1's

Thanks to NumPy because we don’t have to put the array inside a looping statement (I hate to do that ;)). All you have to do is just mention the rows and the columns that you want your array to have inside the numpy.one method.

In [17]:
import numpy as np
# Creating a numpy array of 1’s which should have 3 rows and 4 columns
print(np.ones((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


So the number 3 → rows and 4 → obviously columns.


---



### Create a 3x5 floating-point array filled with 1s

In [45]:
a = np.ones((3,5), dtype = float)
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

###  Create a 3x5 array filled with 3.14

In [19]:
a = np.full((3,5), 3.14)
a

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

### Create an array filled with a linear sequence. Starting at 0, ending at 20, stepping by 2 (this is similar to the built-in range() function).

In [20]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 5) Create an array of five values evenly spaced between 0 and 1

In [46]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 6) Create a 3x3 array of uniformly distributed random values between 0 and 1

In [47]:
a = np.random.random((3, 3))
a

array([[0.41405599, 0.69440016, 0.41417927],
       [0.04995346, 0.53589641, 0.66379465],
       [0.51488911, 0.94459476, 0.58655504]])

### 7) Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1

In [48]:
a = np.random.normal(0, 1, (3, 3))
a

array([[ 0.30017032, -0.35224985, -1.1425182 ],
       [-0.34934272, -0.20889423,  0.58662319],
       [ 0.83898341,  0.93110208,  0.28558733]])

### 8) Create a 3x3 array of random integers in the interval [0, 10)

In [49]:
a = np.random.randint(0, 10, (3, 3))
a

array([[9, 8, 4],
       [0, 1, 9],
       [8, 2, 3]])

### 9) Create a 3x3 identity matrix

In [51]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Filling the numpy arrays with a particular number

Till now we have seen filling the array with 0’s and 1’s but we should also know that numpy allows us to fill the arrays with any specific number of our choice. We can do this with the help of ***numpy.full*** method. For example, let us fill the array with the number **500**.

In [26]:
import numpy as np
# Creating a numpy array of 500’s which should have 3 rows and 4 columns
print(np.full((3, 4), 500))

[[500 500 500 500]
 [500 500 500 500]
 [500 500 500 500]]


With the help of the full method, we can add any number of our choice to our array.



---



## Creating a numpy array of random numbers

***Uniform distribution →*** It is a probability distribution in which all the outcomes are equally likely. For example, tossing a coin has the probability of uniform distribution because the outcomes are a most likely head or a tail. It’s never going to be both at the same time.
The NumPy package library provides us a uniform distribution method to generate random numbers called ***numpy.random.uniform***.

In [27]:
import numpy as np
# Create a 3x3 array of uniformly distributed 
# random values between 0 and 1
print(np.random.random((3, 3)))

[[0.76091526 0.61805179 0.54471495]
 [0.06120702 0.45999785 0.57933614]
 [0.02850748 0.79785236 0.18471567]]


Also, the numpy package library has a seed generator along with the random number generator, with the help of the seed method we can control the sequence of the random numbers being generated. Most of them don’t know the specialty of the seed method and its purpose. To know more about the seed method refer below.

## Why do we need “seed” inside the random number generator?
If we use the seed every time then we get the same sequence of random numbers.




> So, the same seed yields the same sequence of random numbers.



In [54]:
import numpy as np
# Create a random number arrays of size 5
np.random.seed(0)
print(np.random.random(5))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


No matter how many times you execute the above code you get the same random numbers every time. To know the difference just comment on the code (#) and then see the difference. Let us explore the seed method to a bit more extent.
For example, if you use seed(1) and then generate some random numbers they will be the same with the ones you generate later on but with the same seed (1) as shown below.

In [29]:
import numpy as np
# Create a random number arrays of size 5
np.random.seed(1)
print(np.random.random(5))

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01]


In [30]:
print(np.random.random(5))

[0.09233859 0.18626021 0.34556073 0.39676747 0.53881673]


In [31]:
np.random.seed(1)
print(np.random.random(5))

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01]




> ***Same seed same random numbers ensure “Reproducibility”*** — [Quora.com](https://www.quora.com/What-is-seed-in-random-number-generation)



Also, the range of the seed is from 0 and 2**32–1. Don’t just use negative numbers as the seed value, if you do so you will get an error as shown below:



---




---



# Important Numpy mathematical functions
python numpy libary provides several important mathematical functions such as dot product,Multiplication,Broadcasting,mean,standard deviation,min,max and transpose of nd array.

## Multiplication
Function of scalar mutiplication is to multiply consective elements of nd array

In [32]:
u=np.array([1,2,3])
v=np.array([4,5,6])
print(u*v)

[ 4 10 18]


## Dot Product

In [33]:
dot_product=np.dot(u,v)
print(dot_product)

32


## Broadcasting
Term broadcasting stands for situation when we add a certain number to entire matrix.

In [34]:
u_broadcasted=u+1

## Mininum and maximum

In [35]:
minimum_element_of_u=u.min()
maximum_element_of_u=u.max()
print(minimum_element_of_u,maximum_element_of_u)

1 3


## Mean

In [36]:
print("mean of matrix u is ",u.mean())

mean of matrix u is  2.0


## Standard deviation.

In [37]:
print("standard deviation of matrix u is ",u.std())


standard deviation of matrix u is  0.816496580927726


In [38]:
# Sorting Arrays
# Fast Sorting in NumPy: np.sort and np.argsort

import numpy as np

a = np.array([1, 9, 0, 7, 3, 5])
sort = np.sort(a)
print(sort)

[0 1 3 5 7 9]
